spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cap2_db
    username: cs
    password: cs

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      username: cs
      password: cs
      authentication-database: admin
      host: localhost
      port: 27017

kakao:
  api-key: 10966f529d1d7f3bb4b2b17dd8eac4a5
